#+title: Changelog

*** Dependency Log
**** Production
**** Dev
- pytest
- pylint

*** 10-7-2023
- implemented the main method that implements a decode command which takes a bencoded value as input
  and prints the decoded value
*** 10-13-2023
- implements support of decoding integers via the BitTorrent Protocol
- implements support of decoding lists
- add corresponding tests via Pytest
*** 10-16-2023
- add support and testing for decoding dictionaries
- add support for parsing actual torrent files and associated testing
*** 10-20-2023
- add support for parsing torrent files
- add support for calculating info hashes
- support for discovering peers on central servers, participating in the sharing and downloading of a torrent
*** TODO 10-28-2023
- added support for whole torrent file downloads
- TODO: need to add support for multiple peers at once. Via a work queue consisting of each piece that needs to be downloaded.
  The worker (connection with a peer) could pick a piece from the work queue, attempt to download it,
  check the integrity, and write the downloaded piece into a buffer. Any failure (network issue, hashes not matching, peer not
  having the piece etc.) would put the piece back into the work queue to be tried again.
